### ISSUE TITLE
如何更换首页github, more, twitter的图标内容

### ISSUE THREAD

**Issue by zhanls** [sanonz/hexo-theme-concise#15]
sanonz你好，昨天逛hexo themes看到了这个主题，很喜欢这种风格的博客。
clone到本地后初步想法是把icon more换成icon linkedin，请问一下更换icon应该怎么做？

**Comment by sanonz** [comment]
你直接改源代码吧，哈哈

**Comment by zhanls** [comment]
我改不了，因为不知道你这icon不同content代号对应的图标啊，你的icon是用的哪个web服务呢？？我就fontawesome用的最多，你这个我没见过。。

**Comment by sanonz** [comment]
你可以在这个文件里边追加：https://github.com/sanonz/hexo-theme-concise/blob/master/source/css/icons.less

```less
@font-face {
  font-family: 'iconfont';
  src: url('//at.alicdn.com/t/font_556970_8o9d1va0qqia4i.eot');
  src: url('//at.alicdn.com/t/font_556970_8o9d1va0qqia4i.eot?#iefix') format('embedded-opentype'),
  url('//at.alicdn.com/t/font_556970_8o9d1va0qqia4i.woff') format('woff'),
  url('//at.alicdn.com/t/font_556970_8o9d1va0qqia4i.ttf') format('truetype'),
  url('//at.alicdn.com/t/font_556970_8o9d1va0qqia4i.svg#iconfont') format('svg');
}
.iconfont {
  font-family:"iconfont" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.iconfont-close:before {
  content: "\e69a";
}
```

然后html调用
```html
<i class="iconfont iconfont-close"></i>
```
