### ISSUE TITLE
[Q]Can I change avater url

### ISSUE THREAD

**Issue by 82p** [sanonz/hexo-theme-concise#6]
Hi

Can I change avater url in config like following?

_config.yml

```yml

# url or local path
avater: http://path.to/image.jpg
avater: /path/to/image.jpg

```
